export const metadata = {
  title: "Affiliate Disclosure",
  description:
    "How this site earns from qualifying purchases. Amazon Associates disclosure.",
};

export default function DisclosurePage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-[#faf9ff] to-white dark:from-neutral-950 dark:to-neutral-900">
      <div className="mx-auto max-w-3xl px-4 py-12 space-y-6 text-neutral-800 dark:text-neutral-100">
        <h1 className="text-2xl font-semibold">Affiliate Disclosure</h1>

        <p className="text-sm text-neutral-600 dark:text-neutral-300">
          Some links on this site are affiliate links. If you click one of these
          links and make a purchase, we may earn a commission—at no additional
          cost to you.
        </p>

        <section className="space-y-3">
          <h2 className="text-lg font-medium">Amazon Associates</h2>
          <p className="text-sm text-neutral-600 dark:text-neutral-300">
            We are a participant in the Amazon Services LLC Associates Program,
            an affiliate advertising program designed to provide a means for
            sites to earn advertising fees by advertising and linking to
            Amazon.com.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-medium">How we use links</h2>
          <ul className="list-disc pl-5 text-sm text-neutral-600 dark:text-neutral-300 space-y-1">
            <li>Links never change the price you pay.</li>
            <li>Recommendations are generated by our app based on your inputs.</li>
            <li>You are free to ignore any link or choose a different retailer.</li>
          </ul>
        </section>

        <p className="text-xs text-neutral-500 dark:text-neutral-400 pt-4">
          Last updated: {new Date().toISOString().slice(0, 10)}
        </p>
      </div>
    </main>
  );
}
